### ISSUE TITLE
all endpoints are crashing

### ISSUE THREAD

**Issue by wixar172** [abjerner/Skybrud.Social.Instagram#1]
hello,
first of all thank you for making this..
i am facing an issue with the responses from the endpoints.
i was able to get an access token and initiate a service but the software crashes when i try to get a response
here is the code:

 InstagramService service = InstagramService.CreateFromAccessToken(receivedtoken)
// this crashes the software:
 InstagramGetRecentMediaResponse response = service.Tags.GetRecentMedia("nature");

what could be the issue? 
i tried almost every type of response and they all crash the same way, is it something im doing wrong?
thank you for your help

**Comment by abjerner** [comment]
@wixar172 Instagram has recently changed their API guidelines, which also affects how you use and make requests to the API. 

The changes mean that a lot of the features that made the Instagram API awesome, now no longer is possible or at least requires prior approval by Instagram.

Regarding your code example, getting a list of recent media from a hashtag is no longer a supported use case. I can't find the particular page they mentioned this, but instead you somehow have to work with an Instagram Platform Partner to accomplish this. I don't really know what that involves exactly.

You can read more about the review process in general: https://www.instagram.com/developer/review/

As an agency, this has also caused us a lot of hair pulling. For most of our clients using the Instagram API, we have had to disable their Instagram integrations. However for some of the cases, we have made it work while the app is still in sandbox mode (eg. only when requesting media of the client's Instagram account, but not other accounts).

**Comment by wixar172** [comment]
thank you for your quick response, i was hoping that since my app was already accepted by instagram it would still work, but sadly they ruined everything..
best regards
