### ISSUE TITLE
GetAccessTokenFromAuthCode(authUrl) doesn't give access token

### ISSUE THREAD

**Issue by biplovkc** [abjerner/Skybrud.Social.Instagram#3]
This is what I am doing right now
 
``  
 
        static string clientId = ConfigurationManager.AppSettings["client_id"];
        static string clientSecret = ConfigurationManager.AppSettings["client_secret"];
        static string redirectUri = ConfigurationManager.AppSettings["redirectUri"];
```

        InstagramConfig config = new InstagramConfig(clientId, clientSecret, redirectUri, "");
        InstagramOAuthClient client = new InstagramOAuthClient
        {
            ClientId = clientId,
            ClientSecret = clientSecret,
            RedirectUri = redirectUri
        };

        public ActionResult Login()
        {
            string authorizationUrl = client.GetAuthorizationUrl("insta");        

            return Redirect(authorizationUrl); //redirects to OAuth with code as parameter
        }
        public ActionResult OAuth(string code)
        {

            InstagramAccessTokenResponse response = client.GetAccessTokenFromAuthCode(code);
            Session.Add("AuthInfo", response);
            return RedirectToAction("Index");
        }
```
I get error in line 
I_nstagramAccessTokenResponse response = client.GetAccessTokenFromAuthCode(code);_

An exception of type 'System.NullReferenceException' occurred in Skybrud.Social.dll but was not handled in user code

Additional information: Object reference not set to an instance of an object.

I am getting the code values but the access token doesn't work after getting the code

**Comment by abjerner** [comment]
@cybercop I'll look into that ;)

What version of Skybrud.Social are you using?

**Comment by biplovkc** [comment]
0.9.6

**Comment by abjerner** [comment]
@cybercop I haven't been able to reproduce the issue in my end.

Are you sure that neither `ClientId`, `ClientSecret` or `RedirectUri` are empty or null when calling `GetAccessTokenFromAuthCode`? If at least one of them is missing, then I'm able to reproduce the same exception.

**Comment by biplovkc** [comment]
![error1](https://user-images.githubusercontent.com/3874935/30120446-243f895e-9329-11e7-9c9c-3cc4b4af601f.jpg)

![error2](https://user-images.githubusercontent.com/3874935/30120459-2bdcf35e-9329-11e7-8831-1d1474a6d450.jpg)

nope they are not null

**Comment by abjerner** [comment]
The Instagram API is most likely responding with an error, which isn't handled properly in my code. So in your OAuth method, could you try replacing the existing with the following code:

```C#

        // Initialize collection with POST data
        NameValueCollection parameters = new NameValueCollection {
            {"client_id", client.ClientId},
            {"client_secret", client.ClientSecret},
            {"grant_type", "authorization_code"},
            {"redirect_uri", client.RedirectUri},
            {"code", code }
        };

        // Make the call to the API
        string body = SocialUtils.DoHttpPostRequestAndGetBodyAsString("https://api.instagram.com/oauth/access_token", null, parameters);
```

and then post the contents of `body`? The API should respond with a JSON body - even for error responses.

Alternatively, you could try installing `Skybrud.Social.Instagram` (the package in this repository, actually)  instead. Right now you have `Skybrud.Social`, which is currently the stable version, and which has support for a number of services (including Instagram) by default.

`Skybrud.Social` will soon be replaced by individual packages instead, where `Skybrud.Social.Instagram` (still beta'ish at the moment) will be the package for Instagram. `Skybrud.Social.Instagram` already has better error checking than `Skybrud.Social` ;)

**Comment by biplovkc** [comment]
I installed Skybrud.Social.Instagram as you said.
But the error now says invalid client secret.
Which clearly is not

![error1](https://user-images.githubusercontent.com/3874935/30129662-eb83b252-9346-11e7-8e0d-19777318996d.jpg)

![error2](https://user-images.githubusercontent.com/3874935/30129668-f58d0424-9346-11e7-89c3-61bd9345830b.jpg)

![error3](https://user-images.githubusercontent.com/3874935/30129680-ff011e46-9346-11e7-9d60-2e571f359b85.jpg)

I also reset my secret and tried the new secret key but still same error.

If my client secret was wrong would I still get code for access token?

**Comment by abjerner** [comment]
In the screenshot above, doesn't your client secret have a space at the end?

**Comment by biplovkc** [comment]
Ah sorry for the stupidity. it works now thank you! Is there any documentation regarding, how to get some pictures by username? (lets say 20 images)

**Comment by abjerner** [comment]
No worries ;)

Regarding looking up pictures by a given username: you can't. But you can do a search first for the username first to find the ID of the user, and then request images for that user ID.

here's some documentation:

1. [Search users](http://social.skybrud.dk/instagram/endpoints/users/search-users/)
2. [Getting a list of recent media](http://social.skybrud.dk/instagram/endpoints/users/getting-a-list-of-recent-media/)
