### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by rahulmaurya-kiwi** [abjerner/Skybrud.Social.Instagram#4]
I am getting always Pagination.NextMaxId=null and Pagination.NextUrl=null
I think it is due to new update from instagram as:

"pagination": {"next_min_id": "", "min_tag_id": "", "deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}

**Comment by abjerner** [comment]
@rahulmaurya-kiwi  Can you share some more information about your issue? While the `next_max_id` and `min_id` are deprecated, they still work.

You can see one of my examples in the documentation for further information:

http://social.skybrud.dk/instagram/endpoints/tags/getting-recent-media-from-a-tag/

Even though it uses the deprecated properties, it still works.
