### ISSUE TITLE
Will this beta version plug into the skybrud for umbraco, by replacing core.dll and adding the provider.dlls?

### ISSUE THREAD

**Issue by mistyn8** [abjerner/Skybrud.Social.Instagram#5]
Not an issue more a request for info..

Looking to leverage particularly the extended_tweet mode in the twitter provider.
So as per the topic should I be able to replace the core.dll and the provider.dlls and it work with the existing umbraco.skybrud.social implementation?

**Comment by abjerner** [comment]
Hi Mike,

The new providers introduce a number of breaking changes, and I will probably introduce some more before the betas eventually turn into stable releases. The breaking changes are mostly to fix errors I've made in the past, reflect changes in the underlying APIs and simply to give the code a better structure (as Skybrud.Social was started more than five years ago).

Therefore, you won't just be able to switch out the current `Skybrud.Social` with the new core and provider DLLs. I'm pretty sure things will break, although I don't know exactly which parts at the moment.

When stable releases are available of the provider packages used by the Umbraco package (Facebook, Twitter, Instagram and Google), I'll make sure to update the Umbraco package accordingly. If I can find the time, I might even make some beta releases of the Umbraco package as well. I do however not yet know how much work it will take to update the Umbraco package, so I don't really have a time frame for that.

I hope that answers your questions ;)
